accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('', views.Dashboard.as_view(), name='dashboard'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

core/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('accounts.urls')),
    path('', include('youtube.urls')),
]

youtube/urls.py
from youtube import views
from django.urls import path, include

app_name = 'youtube'

urlpatterns = [
    path('authorize/', views.AuthorizeView.as_view(), name='authorize'),
    path('oauth2callback/', views.OAuth2CallBack.as_view(), name='oauth2callback'),
    path('sources/', views.VideoSourceListView.as_view(), name='video_sources'),
    path('sources/create/', views.VideoSourceCreateView.as_view(), name='video_source_create'),
    path('sources/update/<int:pk>/', views.VideoSourceUpdateView.as_view(), name='video_source_update'),
    path('sources/crawl/<int:pk>/', views.CrawlChannelView.as_view(), name='video_source_crawl'),
    path('api/v1/', include('youtube.api.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text'})
    )
    password = forms.CharField(
        max_length=255,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'})
    )

accounts/views.py
from django.views import View
from django.urls import reverse
from accounts.forms import LoginForm
from django.shortcuts import redirect
from youtube.models import YoutubeCredential
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.views.generic.base import TemplateResponseMixin
from oauth2client.contrib.django_util.storage import DjangoORMStorage


@method_decorator(login_required, name='dispatch')
class Dashboard(View, TemplateResponseMixin):
    """
    Class for handling dashboard view
    """
    template_name = 'dashboard.html'

    def get(self, request):
        # Get Google OAuth credential for accessing Youtube Data API
        storage = DjangoORMStorage(
            YoutubeCredential, 'id', request.user.id, 'credential'
        )
        credentials = storage.get()
        return self.render_to_response({'credentials': credentials})


class Login(View, TemplateResponseMixin):
    """
    Class for handling login functionality
    """
    template_name = 'login.html'
    form = LoginForm

    def get(self, request):
        # Checking if user already logged in
        if request.user.is_authenticated:
            return redirect(reverse('accounts:dashboard'))

        form = self.form()
        return self.render_to_response(locals())

    def post(self, request):
        form = self.form(request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            # Checking if valid user
            user = authenticate(username=username, password=password)

            if user:
                # Logging in user
                login(request, user)
                if 'next' in request.GET:
                    return redirect(request.GET.get('next', '/'))
                return redirect(reverse('accounts:dashboard'))
            return self.render_to_response({"form": form, 'errors': 'Invalid user credential.'})
        return self.render_to_response({"form": form, 'errors': form.errors})


class Logout(View):
    """
    Class for handling logout
    """

    def get(self, request):
        # Redirecting user to login page if not logged in
        if not request.user.is_authenticated:
            return redirect(reverse('accounts:login'))

        logout(request)
        return redirect(reverse("accounts:login"))

accounts/templates/dashboard.html
{% extends 'base.html' %}

{% block contents %}
<div class="row">
    <div class="col-sm-12">
        <h1>Dashboard</h1>
        <hr>
        {% if not credentials %}
            <a href="{% url 'youtube:authorize' %}">Create credential for Youtube Data API </a>
        {% else %}
            <p>You have created a authorized credential for accessing Youtube Data API </p>
            <code>{{ credentials }} </code>
        {% endif %}
        <hr>
        <a class="btn btn-primary" href="{% url 'youtube:video_sources'%}">Video Sources</a>
        <a style="float:right" class="btn btn-danger" href="{% url 'accounts:logout'%}">Log out</a>
    </div>
</div>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}

{% block contents %}
<div class="row">
    <div class="col-sm-12">
        <h1>Login</h1>
        <hr>
        <form action="{% url 'accounts:login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                {{ form.password }}
            </div>
            <button type="submit" class="btn btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}